"""
Django settings for edutrellis project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-2!^^*c(t)whrn^4w3xkoqx!1p85e5s!-xh0w+xai7&q*80tt@@'
)

DEBUG = True

ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'myapp',
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'edutrellis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'edutrellis.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'myapp' / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True




# ── Email (Gmail SMTP via App Password) ─────────────────────────────────────
# All outbound store/site email (order confirmations, contact-lead alerts) is
# sent via this account. Signup/profile verification codes moved to SMS (see
# TWO_FACTOR_API_KEY below) — email is no longer in that path. The
# dashboard's Email Settings page has been deactivated — this is the only
# email path now. Hardcoded on purpose, with NO os.environ.get() indirection
# — a stale EMAIL_HOST_USER/PASSWORD env var left over from earlier SMTP
# testing on a dev machine would otherwise silently override these and
# nobody would know.

EMAIL_BACKEND  = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST     = 'smtp.gmail.com'
EMAIL_PORT     = 587
EMAIL_USE_TLS  = True
EMAIL_USE_SSL  = False

# Fail fast rather than hanging the request for 30+ seconds if Gmail's SMTP
# doesn't respond within 10 seconds.
EMAIL_TIMEOUT  = 10

EMAIL_HOST_USER      = 'edutrellisprivatelimited@gmail.com'
EMAIL_HOST_PASSWORD  = 'tnjwlzgzmnexoufo'
DEFAULT_FROM_EMAIL   = f'EduTrellis <{EMAIL_HOST_USER}>'
LEAD_RECIPIENT_EMAIL = EMAIL_HOST_USER

# ── SMS OTP (2Factor.in) ─────────────────────────────────────────────────────
# Signup/profile phone verification goes over SMS via this API key — a plain
# HTTPS call, so it isn't affected by the Gmail/Titan SMTP delivery problems
# or by Railway potentially blocking outbound SMTP on production.
TWO_FACTOR_API_KEY = '12feb4c9-9636-11f1-9cb1-0200cd936042'


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


