from django.urls import path
from myapp import views

urlpatterns = [
    path('', views.home, name='home'),
    path('websitecreation/', views.home2, name='home2'),
    path('store/', views.estore, name='estore'),
    path('store/api/signup/', views.store_signup, name='store_signup'),
    path('store/api/login/', views.store_login, name='store_login'),
    path('store/api/logout/', views.store_logout, name='store_logout'),
    path('store/api/profile/update/', views.store_profile_update, name='store_profile_update'),
    path('store/api/profile/password/', views.store_password_change, name='store_password_change'),
    path('store/api/cart/', views.store_cart_get, name='store_cart_get'),
    path('store/api/cart/add/', views.store_cart_add, name='store_cart_add'),
    path('store/api/cart/update/', views.store_cart_update, name='store_cart_update'),
    path('store/api/cart/remove/', views.store_cart_remove, name='store_cart_remove'),
    path('store/api/checkout/', views.store_checkout, name='store_checkout'),
    path('store/api/checkout/razorpay/verify/', views.store_razorpay_verify, name='store_razorpay_verify'),
    path('store/api/orders/', views.store_orders_list, name='store_orders_list'),
    path('store/api/wallet/', views.store_wallet_get, name='store_wallet_get'),
    path('store/api/contact/', views.store_contact, name='store_contact'),

    path('store/policy/<str:key>/', views.policy_page, name='policy_page'),
    path('store/product/<slug:slug>/', views.product_detail, name='product_detail'),

    path('store/dashboard/', views.dashboard_home, name='dashboard_home'),
    path('store/dashboard/signups/', views.dashboard_signups, name='dashboard_signups'),
    path('store/dashboard/contacts/', views.dashboard_contacts, name='dashboard_contacts'),
    path('store/dashboard/contacts/<int:pk>/delete/', views.dashboard_contact_delete, name='dashboard_contact_delete'),
    path('store/dashboard/categories/', views.dashboard_categories, name='dashboard_categories'),
    path('store/dashboard/categories/add/', views.dashboard_category_add, name='dashboard_category_add'),
    path('store/dashboard/categories/<int:pk>/edit/', views.dashboard_category_edit, name='dashboard_category_edit'),
    path('store/dashboard/categories/<int:pk>/delete/', views.dashboard_category_delete, name='dashboard_category_delete'),
    path('store/dashboard/products/', views.dashboard_products, name='dashboard_products'),
    path('store/dashboard/products/add/', views.dashboard_product_add, name='dashboard_product_add'),
    path('store/dashboard/products/<int:pk>/edit/', views.dashboard_product_edit, name='dashboard_product_edit'),
    path('store/dashboard/products/<int:pk>/delete/', views.dashboard_product_delete, name='dashboard_product_delete'),
    path('store/dashboard/about/', views.dashboard_about, name='dashboard_about'),
    path('store/dashboard/policies/', views.dashboard_policies, name='dashboard_policies'),
    path('store/dashboard/policies/<int:pk>/edit/', views.dashboard_policy_edit, name='dashboard_policy_edit'),
    path('store/dashboard/payment-settings/', views.dashboard_payment_settings, name='dashboard_payment_settings'),
    path('store/dashboard/payments/', views.dashboard_payments, name='dashboard_payments'),
    path('store/dashboard/backup/', views.dashboard_backup, name='dashboard_backup'),
    path('store/dashboard/backup/settings/', views.dashboard_backup_settings, name='dashboard_backup_settings'),
    path('store/dashboard/backup/run/', views.dashboard_backup_run, name='dashboard_backup_run'),
    path('store/dashboard/backup/restore/', views.dashboard_backup_restore, name='dashboard_backup_restore'),
    path('store/dashboard/orders/', views.dashboard_orders, name='dashboard_orders'),
    path('store/dashboard/orders/<int:pk>/status/', views.dashboard_order_status_update, name='dashboard_order_status_update'),
    path('store/dashboard/logout/', views.dashboard_logout, name='dashboard_logout'),

    path('contact/', views.contact_lead, name='contact_lead'),
]
